DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Trilogia CASCADE;
DROP TABLE IF EXISTS Trilogian_osa CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS GenreLiitos_trilogia CASCADE;
