-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Trilogia CASCADE;
DROP TABLE IF EXISTS TrilogianOsa CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS GenreLiitosT CASCADE;
DROP TABLE IF EXISTS GenreLiitosO CASCADE;
